apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: '{{.Values.microservices[0].serviceName}}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{.Values.microservices[0].serviceName}}'
  minReplicas: '{{.Values.microservices[0].minReplicas}}'
  maxReplicas: '{{.Values.microservices[0].maxReplicas}}'
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
