apiVersion: v1
kind: PersistentVolume
metadata:
  name: '{{.Values.microservices[0].serviceName}}'
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
